# -*- coding: utf-8 -*-
"""mrsa_rnaseq_pca.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CckvvDFgYaKBAGktvDUue2A96puh9rXH

## Set up R environment for PCA

First, we'll mount Google Drive to access your data and install the necessary R packages.
"""

# Mount Google Drive to access your files
from google.colab import drive
drive.mount('/content/drive')

"""Now, let's install the R packages needed for data manipulation, VST (if applicable), and PCA. We'll use `tidyverse` for data handling, `DESeq2` for VST, and `ggplot2` for plotting."""

# Commented out IPython magic to ensure Python compatibility.
# Load R magic commands
# IMPORTANT: This cell must be run successfully before any `%%R` cells.
# %load_ext rpy2.ipython

# Commented out IPython magic to ensure Python compatibility.
# %%R
# # Install necessary R packages if not already installed
# if (!requireNamespace("BiocManager", quietly = TRUE)){
#     install.packages("BiocManager")
# }
# 
# if (!requireNamespace("DESeq2", quietly = TRUE)) {
#     BiocManager::install("DESeq2")
# }
# 
# if (!requireNamespace("tidyverse", quietly = TRUE)) {
#     install.packages("tidyverse")
# }
# 
# # Load libraries
# library(tidyverse)
# library(DESeq2)
# library(ggplot2)

"""Next, please specify the path to your CSV file in Google Drive. Make sure it's accessible after mounting your drive. The CSV should contain your raw counts, with rows as genes/features and columns as samples.

### Read Raw Counts and Perform VST

First, specify the full path to your CSV file on Google Drive. The file should contain raw counts with gene IDs as row names (or in the first column) and sample names as column names. Then, we'll use `DESeq2` to apply the Variance Stabilizing Transformation.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# # --- USER INPUT REQUIRED --- #
# # IMPORTANT: Replace 'path/to/your/raw_counts.csv' with the actual path to your CSV file in Google Drive.
# # Example: '/content/drive/MyDrive/my_data/raw_counts.csv'
# # csv_file_path <- "/content/drive/MyDrive/mrsa/rnaseq/countMatrix.csv"
# rds_file_path <- "/content/drive/MyDrive/mrsa/rnaseq/countMatrix.rds"
# # --- END USER INPUT --- #
# 
# # Read the raw counts data
# # Assuming the first column is gene IDs and subsequent columns are sample counts
# raw_counts <- readRDS(rds_file_path)
# dim(raw_counts)
# 
# # filter for the following colnames
# filter_patterns <- c('1a', '2a', '5a', '6a', '1b', '2b', '5b', '6b')
# 
# # Get column names from the raw_counts object
# all_colnames <- colnames(raw_counts)
# 
# # Keep the first column (gene IDs) which is 'ENSEMBL_GeneID'
# gene_id_col_name <- all_colnames[1]
# 
# # Initialize a vector to store column names to keep after filtering by pattern
# columns_to_keep_original <- c(gene_id_col_name)
# 
# # Find columns matching any of the filter patterns, excluding the first column
# for (pattern in filter_patterns) {
#   matching_cols <- grep(pattern, all_colnames[-1], value = TRUE)
#   columns_to_keep_original <- c(columns_to_keep_original, matching_cols)
# }
# 
# # Ensure uniqueness and order
# columns_to_keep_original <- unique(columns_to_keep_original)
# 
# # Filter the raw_counts data frame based on original names
# raw_counts_filtered_initial <- raw_counts[, columns_to_keep_original]
# 
# cat("\nDimensions of initially filtered raw counts data:", dim(raw_counts_filtered_initial), "\n")
# print(head(raw_counts_filtered_initial))
# 
# # --- Step 1: Rename columns to the desired format with _Rep1/_Rep2 suffixes ---
# 
# samplekey <- list('1a'='Mock_7hpi_1a','2a'='MRSA_7hpi_2a','5a'='Mock_24hpi_5a','6a'='MRSA_24hpi_6a',
#                   '1b'='Mock_7hpi_1b','2b'='MRSA_7hpi_2b','5b'='Mock_24hpi_5b','6b'='MRSA_24hpi_6b')
# 
# # Get current column names of the initially filtered raw counts
# current_colnames_for_renaming <- colnames(raw_counts_filtered_initial)
# 
# # Initialize new column names vector, keeping the first column (gene_id_col_name) unchanged
# renamed_colnames <- current_colnames_for_renaming
# 
# # Iterate through sample columns (starting from the second column)
# for (i in 2:length(current_colnames_for_renaming)) {
#   original_name <- current_colnames_for_renaming[i]
# 
#   # Determine replicate suffix based on 'L006' or 'L007'
#   replicate_suffix <- ""
#   if (grepl("L006", original_name, fixed = TRUE)) {
#     replicate_suffix <- "_Rep1"
#   } else if (grepl("L007", original_name, fixed = TRUE)) {
#     replicate_suffix <- "_Rep2"
#   }
# 
#   # Find matching key in samplekey and rename
#   found_key <- FALSE
#   for (key in names(samplekey)) {
#     if (grepl(key, original_name, fixed = TRUE)) { # Use fixed=TRUE for literal string matching
#       new_base_name <- samplekey[[key]]
#       renamed_colnames[i] <- paste0(new_base_name, replicate_suffix)
#       found_key <- TRUE
#       break # Found the key, move to next original_name
#     }
#   }
# 
#   # If no key from samplekey was found, and there was a replicate suffix, keep original name + suffix
#   # This handles cases where a pattern from filter_patterns was matched but no samplekey entry existed.
#   if (!found_key && replicate_suffix != "") {
#       renamed_colnames[i] <- paste0(original_name, replicate_suffix)
#   } else if (!found_key) { # If no key or suffix found, keep original name
#       renamed_colnames[i] <- original_name
#   }
# }
# 
# # Apply the new column names to the data frame
# colnames(raw_counts_filtered_initial) <- renamed_colnames
# 
# cat("\nColumn names after initial renaming to Rep1/Rep2 format:\n")
# print(colnames(raw_counts_filtered_initial))
# print(head(raw_counts_filtered_initial))
# 
# # --- Step 2: Average replicate columns ---
# 
# # Initialize a list to store averaged columns
# averaged_cols_data <- list()
# final_sample_names <- c(gene_id_col_name) # Start with the gene ID column name
# 
# # Get the base names (e.g., 'Mock_7hpi_1a') from the values of samplekey
# unique_sample_bases <- unique(unlist(samplekey))
# 
# for (base_name in unique_sample_bases) {
#   rep1_col_name <- paste0(base_name, "_Rep1")
#   rep2_col_name <- paste0(base_name, "_Rep2")
# 
#   has_rep1 <- rep1_col_name %in% colnames(raw_counts_filtered_initial)
#   has_rep2 <- rep2_col_name %in% colnames(raw_counts_filtered_initial)
# 
#   if (has_rep1 && has_rep2) {
#     # Both replicates exist, average them
#     averaged_values <- rowMeans(raw_counts_filtered_initial[, c(rep1_col_name, rep2_col_name)], na.rm = TRUE)
#     averaged_cols_data[[base_name]] <- averaged_values
#     final_sample_names <- c(final_sample_names, base_name)
#   } else if (has_rep1) {
#     # Only Rep1 exists, use it as is
#     averaged_cols_data[[base_name]] <- raw_counts_filtered_initial[, rep1_col_name]
#     final_sample_names <- c(final_sample_names, base_name)
#   } else if (has_rep2) {
#     # Only Rep2 exists, use it as is
#     averaged_cols_data[[base_name]] <- raw_counts_filtered_initial[, rep2_col_name]
#     final_sample_names <- c(final_sample_names, base_name)
#   } else {
#     warning(paste("No replicates (_Rep1 or _Rep2) found for base name:", base_name, ". Skipping."))
#   }
# }
# 
# # Combine the gene ID column with the averaged data
# raw_counts_flt <- cbind(raw_counts_filtered_initial[[gene_id_col_name]], as.data.frame(averaged_cols_data))
# colnames(raw_counts_flt) <- final_sample_names
# 
# cat("\nDimensions of filtered, renamed, and averaged raw counts data (raw_counts_flt):", dim(raw_counts_flt), "\n")
# print(head(raw_counts_flt))
#



"""### Create Sample Metadata Table

Now, let's create a metadata table from the renamed column names. This table will be used to define experimental conditions for DESeq2 and for coloring/shaping points in the PCA plot.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# # Get the sample names (excluding the gene ID column), which are now the averaged sample names
# sample_ids <- colnames(raw_counts_flt)[-1]
# 
# # Initialize vectors for condition and hpi
# conditions <- character(length(sample_ids))
# hpis <- character(length(sample_ids))
# 
# # Parse sample_ids to extract condition and hpi
# for (i in 1:length(sample_ids)) {
#   name <- sample_ids[i]
# 
#   # Extract condition (Mock or MRSA)
#   if (grepl("Mock", name)) {
#     conditions[i] <- "Mock"
#   } else if (grepl("MRSA", name)) {
#     conditions[i] <- "MRSA"
#   } else {
#     conditions[i] <- "Unknown_Condition"
#   }
# 
#   # Extract hpi (7hpi or 24hpi)
#   if (grepl("7hpi", name)) {
#     hpis[i] <- "7hpi"
#   } else if (grepl("24hpi", name)) {
#     hpis[i] <- "24hpi"
#   } else {
#     hpis[i] <- "Unknown_hpi"
#   }
# }
# 
# # Create the metadata data frame
# sample_metadata <- data.frame(
#   sample_id = sample_ids,
#   condition = factor(conditions),
#   hpi = factor(hpis),
#   row.names = sample_ids # Set row names to sample IDs for easy merging later
# )
# 
# # Add a combined group factor for plotting
# sample_metadata$group <- factor(paste(sample_metadata$condition, sample_metadata$hpi, sep = "_"))
# 
# cat("\nSample Metadata Table:\n")
# print(sample_metadata)



# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# # Convert to a matrix
# # Now using raw_counts_flt (filtered and averaged data) instead of raw_counts
# raw_counts_matrix <- as.matrix(raw_counts_flt[, -1]) # Exclude the gene ID column for the matrix
# 
# # Check the dimensions and a glimpse of the data
# cat("Dimensions of raw counts matrix:", dim(raw_counts_matrix), "\n")
# print(head(raw_counts_matrix))
# 
# # For DESeq2, we need a colData (sample information) dataframe.
# # This will now use the generated sample_metadata table
# 
# sample_names <- colnames(raw_counts_matrix)
# 
# # Ensure that sample_metadata has the same row names (sample_ids) as the columns in raw_counts_matrix
# # and that they are in the same order.
# # This check is crucial for DESeqDataSetFromMatrix
# if (!identical(sample_names, rownames(sample_metadata))) {
#   stop("Mismatch between sample names in raw counts matrix and sample metadata row names!")
# }
# 
# # Create a DESeqDataSet object using the actual sample_metadata
# dds <- DESeqDataSetFromMatrix(countData = round(raw_counts_matrix), # DESeq2 expects integer counts
#                               colData = sample_metadata,
#                               design = ~ condition + hpi) # Design based on our metadata
# 
# # Perform Variance Stabilizing Transformation (VST)
# vsd <- vst(dds, blind = TRUE) # blind = TRUE is recommended for PCA and unsupervised analyses
# 
# # Extract the VST transformed counts
# vst_counts <- assay(vsd)
# 
# cat("\nDimensions of VST transformed counts:", dim(vst_counts), "\n")
# print(head(vst_counts))

"""### Perform Principal Component Analysis (PCA)

Now that we have the VST-transformed counts, we can perform PCA to reduce dimensionality and visualize the sample relationships.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# # Transpose the VST counts matrix so samples are rows and genes are columns for PCA
# vst_counts_t <- t(vst_counts)
# 
# # Perform PCA using prcomp
# pca_result <- prcomp(vst_counts_t)
# 
# # Get the PCA loadings (eigenvectors) for each component
# cat("\nPCA Loadings (first 5 genes for PC1 and PC2):\n")
# print(head(pca_result$rotation[, 1:2]))
# 
# # Get the PCA scores (coordinates of the samples in the new component space)
# pca_scores <- as.data.frame(pca_result$x)
# 
# cat("\nPCA Scores (first 5 samples for PC1 and PC2):\n")
# print(head(pca_scores))
# 
# # Calculate the percentage of variance explained by each principal component
# variance_explained <- (pca_result$sdev^2 / sum(pca_result$sdev^2)) * 100
# 
# cat("\nPercentage of variance explained by each PC:\n")
# print(head(variance_explained))
# 
# # Now, merge pca_scores with sample_metadata for plotting
# # Ensure row names match for merging
# if (!identical(rownames(pca_scores), rownames(sample_metadata))) {
#   stop("Mismatch between PCA scores row names and sample metadata row names!")
# }
# 
# plot_data <- cbind(pca_scores, sample_metadata)
# 
# # Plot PCA results using ggplot2
# p <- ggplot(plot_data, aes(x = PC1, y = PC2)) + # Removed 'label' aesthetic from main aes, removed 'color' as fill will now control internal color
#   geom_point(aes(fill = group), shape = 21, size = 8, alpha = 0.8, color = "black", stroke = 0.5) + # Increased point size for better visibility, added black outline
#   # geom_text(vjust = -0.8, hjust = 0.5, size = 3, check_overlap = TRUE) + # Removed geom_text to hide labels
#   xlab(paste0("PC1 (", round(variance_explained[1], 2), "% variance)")) +
#   ylab(paste0("PC2 (", round(variance_explained[2], 2), "% variance)")) +
#   ggtitle("PCA of VST Transformed Counts with Sample Metadata") +
#   scale_fill_manual(values = c("Mock_7hpi" = "darkblue",
#                                "Mock_24hpi" = "cornflowerblue",
#                                "MRSA_7hpi" = "red",
#                                "MRSA_24hpi" = "darkgoldenrod")) + # Custom colors for combined groups, changed to scale_fill_manual
#   theme_minimal() +
#   theme(legend.position = "right",
#         panel.grid.major = element_blank(), # Remove major grid lines
#         panel.grid.minor = element_blank(), # Remove minor grid lines
#         panel.border = element_rect(color = "black", fill = NA, linewidth = 1), # Add black border to the plot
#         aspect.ratio = 1, # Make the plot square
#         axis.title.x = element_text(face = "bold", size = 14), # Bold and increase font for x-axis title
#         axis.title.y = element_text(face = "bold", size = 14), # Bold and increase font for y-axis title
#         axis.text.x = element_text(size = 12), # Increase font for x-axis numbers
#         axis.text.y = element_text(size = 12)) + # Increase font for y-axis numbers
#   coord_fixed(ratio = 1) # Ensure aspect ratio is 1:1 for a square plot
# 
# print(p)

"""### Export Plot as SVG

Finally, we'll save the PCA plot as an SVG file for high-quality vector graphics.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# # --- USER INPUT REQUIRED --- #
# # Specify the desired path and filename for the SVG file in Google Drive.
# output_svg_path <- "/content/drive/MyDrive/mrsa/rnaseq/transcriptome_mrsa_pca.svg"
# # --- END USER INPUT --- #
# 
# # Save the plot as an SVG file
# ggsave(filename = output_svg_path, plot = p, device = "svg", width = 8, height = 8)
# 
# cat("PCA plot saved to:", output_svg_path, "\n")

